# Generated by Django 5.2 on 2025-04-11 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='precio',
            table='precio',
        ),
    ]
