# Generated by Django 5.2 on 2025-04-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'marca',
            },
        ),
    ]
