# Generated by Django 5.2 on 2025-04-11 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carrito', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleCarrito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carrito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carrito.carritocompras')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.producto')),
            ],
            options={
                'db_table': 'detalle_carrito',
            },
        ),
    ]
