# Generated by Django 5.1.7 on 2025-04-10 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('crear', models.BooleanField()),
                ('eliminar', models.BooleanField()),
                ('actualizar', models.BooleanField()),
                ('ver', models.BooleanField()),
            ],
            options={
                'db_table': 'permiso',
            },
        ),
    ]
